mongodb/bson-rust

examples/decode.rs, examples/encode.rs, src/bson.rs, src/decoder.rs, src/encoder.rs, src/lib.rs, src/spec.rs
Hey, I was browsing around and found your library. I thought it looked a little scruffy and wanted to help improve it. I am open to feedback, of course.
The big changes are the removal of `Encoder` and `Decoder` structs, and replacing them with functions. These functions are generic over `Read` and `Write` and don't enforce dynamic dispatch. The internals of these functions have also been made private, since I don't see much use for them.
I made the internal modules private in favor of the re-exports, and removed the `ToBson` trait since it didn't seem to be doing much.
I also filled in some of the missing documentation (run `cargo doc --open` to review it).
Finally, I cleaned up some code constructs that aren't needed in Rust 1.0.0 anymore.
=> Many Improvements

src/bson.rs, src/lib.rs, src/ordered.rs
Hiya! This is a drop-in replacement for the BTreeMap BSON document that maintains an ordering of the keys based on insertion. This is necessary for certain types of operations, such as [sorting](http://docs.mongodb.org/manual/reference/method/cursor.sort/), where the sort precedence relies on the key ordering.
=> Insertion-ordered BSON documents

src/encoder.rs
The boolean encodings are mixed. http://bsonspec.org/spec.html
=> Fix boolean encoding

Cargo.toml, examples/encode.rs, src/bson.rs, src/decoder.rs, src/encoder.rs, src/lib.rs, src/oid.rs, tests/lib.rs, tests/oid.rs
This replaces the generic [u8; 12] representation of OIDs with an ObjectId struct, providing some more type safety around OIDs that are passed around and allowing valid OIDs to be generated client-side. This is a breaking change -- existing code must use `ObjectId::with_bytes()` and `oid.bytes()` to pass and get raw [u8; 12] oid representations.
Opening a PR since this is a moderately-sized update, @zonyitoo :)
[Relevant PR in mongo-rust-driver-prototype.](https://github.com/mongodbinc-interns/mongo-rust-driver-prototype/pull/75)
=> ObjectId container and generator

src/bson.rs, src/ordered.rs, tests/lib.rs
For the logging functionality in the MongoDB driver, we need to be able to print out documents in the format that they would appear in the shell. The ability to print the documents in a readable format would be useful for almost anyone using BSON, though.
=> Format display

src/oid.rs
Replaces the [0; 3] check for MACHINE_BYTES with an Option check.
Also implements Clone for Errors by manually cloning io::Error. Not sure why io::Error doesn't implement Clone, but it inhibits the functionality and usability of structs that have owned Error fields like Cursor in the [mongo driver](https://github.com/kyeah/mongo-rust-driver-prototype/commit/d534c4156ce1092e4f87167c76fb6fd5f13a8049#diff-90872b5d72d7eb7ca5dac072e26fb38eR228).
=> Use option for mutable static

src/decoder.rs, src/encoder.rs, tests/modules/encoder.rs
Currently UtcDatetime is encoded as a `i64` from the chronos timestamp, however the chronos timestamp is returned in seconds since epoch(https://lifthrasiir.github.io/rust-chrono/chrono/datetime/struct.DateTime.html#method.timestamp).
According to the BSON spec a UtcDateTime should be encoded as miliseconds since epoch: http://bsonspec.org/spec.html
> UTC datetime - The int64 is UTC milliseconds since the Unix epoch.
This pull request attempts to solve this issue. 
(I've only been using rust for a few days now, so I'd love to know if this could be done better :))
=> Fix UtcDatetime en/decoding

src/ordered.rs, tests/modules/ordered.rs
Another small ergonomics improvement. Before:
```rust
let mut doc = Document::new();
doc.insert("first".to_string(), Bson::I32(1));
```
After:
```rust
let mut doc = Document::new();
doc.insert("first", Bson::I32(1));
```
Also contains a minor performance improvement, removes one clone of the key.
=> Allow string slices as keys for insertion

src/macros.rs, src/ordered.rs, tests/modules/ordered.rs
Another convenience improvement. Before:
```rust
let mut doc = Document::new();
doc.insert("first", Bson::I32(1));
```
After:
```rust
let mut doc = Document::new();
doc.insert("first", 1i32);
```
Don't worry, I think I'm done now :-P.
=> Allow any type that converts into bson for insert

src/bson.rs, src/lib.rs, src/oid.rs, src/ordered.rs, tests/modules/ordered.rs
There's one annoyance left when working with the bson crate for our use case, getting to the inner typed values is quite verbose:
```rust
let truth = match document.get("truth") {
Some(&Bson::Boolean(b)) => b,
_ => panic!("truth is not a boolean")
};
let text = match document.get("text") {
Some(&Bson::String(ref s)) => s,
_ => panic!("text is not a string")
};
```
I've been thinking about a way to make this pattern more convenient. This pull is one way to go about it:
```rust
let truth = try!(document.get_bool("truth"));
let text = try!(document.get_str("text"));
```
Do you like this direction? If so I'll implement the remaining getters.
=> Helpers to directly get inner values

src/bson.rs
First fix `From<String>`: no need to get owning when you own object inside conversion.
Second fix `From<&String>`: useful when content already has borrowed by `ref` keyword.
=> Fix String conversion cases

src/oid.rs, tests/modules/oid.rs
Make ObjectId usable within structs that implement encodable and decodable. Serializes to and from a hex string.
This is a step towards making structs directly serializable to bson.
=> Support encoding and decoding of object ids

src/bson.rs, src/oid.rs, tests/lib.rs
Existing `ObjectId` display inside `Bson` is unsafe - it uses `from_utf8_unchecked()` when it has no right to do so, because the bytes contained inside `ObjectId` are absolutely not guaranteed to form valid UTF-8 data.
This PR makes `Display` implementation for `Bson` to delegate to `ObjectId`'s `Display` implementation, printing it as a hex string. Additionally, `Display` implementation for `Bson` is optimized in order not to allocate more than necessary.
Note that even though I've removed inherent `to_string()` method on `ObjectId`, its API is not broken because `to_string()` is now available through the `Display` implementation and it gives the same result as before.
=> Improved ObjectId and Bson display

Cargo.toml, serde-tests/Cargo.toml, serde-tests/test.rs.in, src/decoder/error.rs, src/decoder/serde.rs, src/encoder/error.rs, src/encoder/serde.rs
Updates serde to 0.7. As noted in #24, this is a breaking change :(
=> Update serde to 0.7

Cargo.toml, src/decoder/serde.rs, src/lib.rs, src/ordered.rs
Discussion in #35 .
Request for comments!
=> Use linked-hash-map to implement OrderedDocument

src/oid.rs
I found it a bit inconvenient sometimes that I could not copy-paste object id's from debug output. This pull fixes that.
=> Show object id formatted as string in debug trait and derive Hash

Cargo.toml, src/decoder/serde.rs, src/encoder/error.rs, src/encoder/serde.rs, tests/serde.rs
The biggest change is the new Serializer API which provides a better way to handle what used to be `Vec<State>` inside `Encoder`.
Before:
```rust
#[inline]
fn serialize_seq<V>(&mut self, mut visitor: V) -> EncoderResult<()>
where V: SeqVisitor,
{
let len = visitor.len().unwrap_or(0);
let values = Vec::with_capacity(len);
self.state.push(State::Array(values));
while let Some(()) = try!(visitor.visit(self)) { }
let values = match try!(self.pop()) {
State::Array(values) => values,
state => return Err(EncoderError::InvalidState(state)),
};
self.state.push(State::Bson(Bson::Array(values)));
Ok(())
}
#[inline]
fn serialize_seq_elt<T>(&mut self, value: T) -> EncoderResult<()>
where T: Serialize,
{
try!(value.serialize(self));
let value = match try!(self.pop()) {
State::Bson(value) => value, …
```
=> Update to serde 0.8

src/oid.rs
Hey! This is a very lazy response to #38 to fix the OID_COUNTER race condition that occurs between `count_generation` and `count_is_big_endian`. There may be a nicer way that keeps the two tests separate, but let's get this out of the way so we can release v0.8.
As a bonus, this will also test that OID_COUNTER is incremented on `gen_count`.
=> Combine oid counter generation tests

src/decoder/mod.rs, src/encoder/mod.rs, tests/modules/encoder_decoder.rs
In the bson spec, a `code_w_s` object is defined as:
```
code_w_s 	::= 	int32 string document 	Code w/ scope
```
On the decoding side, that means we have to read off an `i32` before reading `string` or `document`. On the encoding side, that means we have to add `+4` to the buffer length instead of `+1` (because an i32 is 4 bytes). I tested that this behavior matches up with the golang mongo driver (mgo).
=> Fix JavaScriptCodeWithScope encoding and decoding

src/bson.rs
Hello! After switching over to serde_json, I noticed a small discrepancy in converting numerical values to Bson. 
Looking at the [Number code](https://github.com/serde-rs/json/blob/master/json/src/number.rs#L55-L63), `as_i64` will cast unsigned values to i64, while floating points will return `None`, so we are missing the floating-point conversion here.
=> Fix json f64 value conversion

src/bson.rs
This makes things a little more convenient by allowing us to call `bson_val.into()`, `json_val.into()`, etc, and giving us a more performant, consuming transformation method.
This also allows us to plug bson values into any interface that relies on `From<Value>` or `Into<Value>`.
Keeping `from_json`, `to_json` for backwards-compatibility, and adding an appropriate `into_json` consumer.
=> Implement From/Into traits for Value

Cargo.toml, README.md, src/bson.rs, src/compat/mod.rs, src/compat/u2f.rs, src/decoder/serde.rs, src/encoder/error.rs, src/encoder/serde.rs, src/lib.rs, tests/serde.rs
* Disallow `u16`, `u32` and `u64` to be serialize to / deserialize from BSON
=> Disallow serde serialize/deserialize unsigned integer types

src/decoder/mod.rs, src/lib.rs, tests/modules/encoder_decoder.rs
MongoDB has a bug where it can return bson responses that contain strings with invalid UTF-8 encoding: https://jira.mongodb.org/browse/SERVER-24007
This bug has been open since 2016 and no fix is in sight, so we need a workaround in the `mongo_driver` crate. This commit adds a separate decode function that allows you to get lossy UTF-8 conversion. We will use this function when parsing error responses from Mongo.
=> Add decode_document_utf8_lossy

Cargo.toml, src/ordered.rs, tests/modules/ordered.rs
Since the last time the `linked-hash-map` dependency was updated, it added an entry API to mimic that of the standard library for modifying an entry in the map in-place to get around borrow checker issues when trying to get and insert at the same time. This PR adds a thin wrapper around this functionality for the underlying map used by a `Document`.
I attempted to implement the `entries` method as well, but due to [this](https://github.com/contain-rs/linked-hash-map/pull/89) not yet being released on crates.io, it wasn't working, so I didn't include it in this PR.
=> add entry API for Document

src/bson.rs, src/decoder/serde.rs, src/lib.rs, tests/serde.rs
Currently, there is no good way to deserialize the BSON timestamp type. The only thing that works is deserializing into the `Bson` enum, but that doesn't provide any compile-time guarantees that the value is actually a timestamp type. Following the example of `bson::UtcDateTime`, I implemented a timestamp type that can be used when deserializing.
=> add TimeStamp type to facilitate deserialization

src/decoder/serde.rs, tests/serde.rs
Hello,
I have recently attempted to use the new `bson::TimeStamp` type to decode an optime returned by the `replSetGetStatus` MongoDB command.
The value that I got was different from the result of `rs.status()`.
After a bit of investigation I noticed the timestamp is converted to big endian before it is masked and shifted: https://github.com/zonyitoo/bson-rs/blob/master/src/decoder/serde.rs#L595
I am not familiar with the protocol but other clients (including the bson package in the mongodb repo) seem to use little endian encoding for the values of the timestamp:
* Go Client: https://github.com/mongodb/mongo-go-driver/blob/master/bson/value.go#L820
* Comment in the official MongoDB codebase: https://github.com/mongodb/mongo/blob/master/src/mongo/bson/timestamp.cpp#L51-L52
Is this indeed a …
=> TimeStamp type uses incorrect endianness?

README.md
Querying a document with a string id doesn't work. Instead, you must wrap it in an ObjectId!
=> Edit example in README.md

src/encoder/serde.rs, tests/serde.rs
The `bson::TimeStamp` type does not currently implement `serde::Serialise`.
As a result things like the example below fail to compile.
```rust
use bson::TimeStamp;
#[derive(Serialise)]
pub struct Foo {
ts: TimeStamp,
}
```
This PR would implement `Serialise` for `bson::TimeStamp` so the above code compiles.
=> Implement TimeStamp  serde serialisation

src/bson.rs, src/decoder/error.rs, src/decoder/serde.rs, src/encoder/error.rs, src/encoder/mod.rs, src/encoder/serde.rs, src/oid.rs, src/ordered.rs, src/spec.rs
* remove several unnecessary allocations: `clone()`/`to_owned()`/`to_string()`)
* remove `ref`-`deref` noops for `Copy` types
* `#[derive]` some useful std traits for certain types for better interoperability
* replace `write!(formatter, "string literal")` with `write_str()`
* remove redundant uses of `.iter()` in `for` loops over `&T: IntoIterator<&T::Item>`
=> Code cleanup

Cargo.toml, src/bson.rs, src/decimal128.rs, src/decoder/mod.rs, src/decoder/serde.rs, src/encoder/mod.rs, src/encoder/serde.rs, src/lib.rs, src/ordered.rs, src/spec.rs, tests/lib.rs, tests/modules/encoder_decoder.rs, tests/modules/ordered.rs, tests/modules/ser.rs
Hello!
I wanted to pull in the work @zonyitoo has done in the past to allow support for [Decimal128](https://github.com/mongodb/specifications/tree/master/source/bson-decimal128). 
This PR:
@saghm and @kyeah if either of you have time for a review, I would really appreciate it. 
Thank you for your time!
=> Add Decimal128 support

serde-tests/Cargo.toml, src/decoder/serde.rs
There were a couple of warnings generated from the library itself, so I removed the duplicate imports that caused them as well.
=> fix errors and warnings with serde tests

.travis.yml, Cargo.toml, src/lib.rs, src/oid.rs, tests/modules/oid.rs
Hello o/
I made a PR last week to compat for WASM compilation, adding a WASM specific method to use random bytes arrays to substitute a call to `libc` and getting `hostname`. In the discussion there, @saghm pointed out MongoDB drivers are now transitioning to use 5 random bytes instead of `process_id` and `machine_id` ([spec](https://github.com/mongodb/specifications/blob/master/source/objectid.rst#id3)). This PR implements that.
In addition to using random bytes, this PR also:
This would be probably a semver major in semver terms, but I am not sure how you'd want to handle that (or deprecation for that matter).
Thank you for your time!
=> use random byte array instead of process_id and machine_id

src/bson.rs, src/ordered.rs
This includes both a full set of `as_<type>_mut` methods on the `Bson` type, as
well as `get_<type>_mut` methods on the `OrderedDocument` type.
Copy types also implement these methods, to facilitate the pattern of
modifying a document by using:
```rust
let mut bson_doc = doc!{"number": 14};
let number = bson_doc.get_i32_mut("number");
*number = 15;
println!("{}", bson_doc); // { number: 15 }
```
`Bson::as_null` is not given a mutable alternative, as there is only one
possible unit value.
=> Add mutable accessors for Bson variants.

Cargo.toml
I mainly did this PR for the case that #125 doesn't end up being merged. It reduces the number of dependencies a little and enables decimal128 on docs.rs. That second part is also useful if #125 is not being merged.
=> Turn off default features of decimal and enable decimal128 in the docs

src/bson.rs, tests/modules/bson.rs
This PR new `From<>` implementations to Bson to cover `Vec<T>`, &[T] objects, and &T (where T implements Into<Bson> + Clone).  Comparable impls exist in serde_json::Value, which is, I think, a good reference point for how the Bson type should operate.  Having these impls in place eliminates a lot of manual cloning.
Caveat: When using this branch in the mongodb crate, there is one type inference break:  Because the `From<Array>` implementation (== `From<Vec<Bson>>`) was replaced by `From<Vec<T>> where T: Into<Bson>`, `Bson::from(Vec::new())` now complains that it needs to know the full type of `Vec::new()`.  The problem is resolved by using `Bson::Array(Vec::new())` instead of `Bson::from`.  It also only shows up in case of a Vec of unspecified type, which means it should not affect …
=> Add more Bson From<> implementations for better ergonomics.

README.md, examples/decode.rs, examples/encode.rs, serde-tests/Cargo.toml, serde-tests/test.rs, src/bson.rs, src/encoder/mod.rs, src/lib.rs, src/macros.rs, tests/lib.rs, tests/modules/bson.rs, tests/modules/encoder_decoder.rs, tests/modules/macros.rs, tests/modules/ordered.rs, tests/modules/ser.rs, tests/serde.rs
Allow bson! and doc! macros to work without importing both.
Also update imports and documentation to work without using extern crate everywhere.
I didn't update the fuzz tests because I'm not sure how they're run, so I wouldn't be able to test them properly.
=> Clean macro imports

.evergreen/check-clippy.sh, examples/encode.rs, src/bson.rs, src/compat/u2f.rs, src/decimal128.rs, src/decoder/error.rs, src/decoder/mod.rs, src/decoder/serde.rs, src/encoder/error.rs, src/encoder/mod.rs, src/encoder/serde.rs, src/lib.rs, src/oid.rs, src/ordered.rs, src/spec.rs, tests/lib.rs, tests/modules/bson.rs, tests/modules/encoder_decoder.rs, tests/modules/macros.rs, tests/modules/mod.rs, tests/modules/oid.rs, tests/modules/ordered.rs, tests/modules/ser.rs, tests/serde.rs
I've updated the BSON library to use the same rustfmt config as the driver and reformatted it, as well as fixed all of the clippy lints that don't require breaking changes and whitelisted the rest.
=> Fix failing evergreen lint

src/decoder/serde.rs, src/encoder/serde.rs, tests/serde.rs
[RUST-305](https://jira.mongodb.org/browse/RUST-305)
As discussed in person on Monday, this fixes a bug where the library deserializes all binary subtypes into subtype 0 (generic) regardless of the original subtype that was being deserialized. This occurred due to the fact that the deserialize implementation for the bson Decoder called `visit_bytes` on the visitor; while it allowed `Bson::Binary` to be deserialized into `Vec<u8>`, it also caused the subtype to be ignored in the case that `Bson` was getting deserialized back into `Bson` (which occurs most often in cases where a struct that derives `Deserialize` contains a field of type `Document` or `Bson`). This fixes that bug by calling `visit_bytes` in the case that the subtype of the `Binary` being deserialized is generic, and instead …
=> RUST-305 Fix deserialization of non-generic binary

src/decoder/error.rs, src/decoder/mod.rs
[RUST-217](https://jira.mongodb.org/browse/RUST-217)
This PR adds the key to the error returned when encountering an unsupported/corrupt BSON type.
=> RUST-217 Rephrase unsupported/corrupt BSON messages

serde-tests/test.rs, src/decoder/error.rs, src/decoder/mod.rs, src/decoder/serde.rs, src/document.rs, src/encoder/error.rs, src/encoder/serde.rs, src/oid.rs, tests/modules/ser.rs
[RUST-430](https://jira.mongodb.org/browse/RUST-430) / [RUST-437](https://jira.mongodb.org/browse/RUST-437) / [RUST-443](https://jira.mongodb.org/browse/RUST-443) / [RUST-444](https://jira.mongodb.org/browse/RUST-444) / [RUST-312](https://jira.mongodb.org/browse/RUST-312)
This PR makes a number of improvements to the errors in the BSON library. It also fixes a bug where the serde `deny_unknown_fields` attribute was being ignored.
=> Various error improvements

README.md, src/lib.rs, src/macros.rs
[RUST-438](https://jira.mongodb.org/browse/RUST-438)
This PR updates the library documentation for the `bson` crate. It is heavily influenced by [the library docs for `serde_json`](https://docs.rs/serde_json/1.0.53/serde_json/).
=> RUST-438 Add more detailed documentation examples

src/bson.rs, src/decimal128.rs, src/decoder/error.rs, src/decoder/mod.rs, src/encoder/mod.rs, src/lib.rs, src/spec.rs, tests/spec/corpus.rs
[RUST-445](https://jira.mongodb.org/browse/RUST-455)
This PR adds basic support for the BSON decimal128 type outside of the `"decimal128"` feature flag. It exposes the `Decimal128` struct but with no functionality, so it can only be created by deserializing existing documents (e.g. from the DB).
=> RUST-445 Round trip decimal128 values

src/spec.rs, tests/modules/macros.rs
bson-rust is missing the new binary subtype 6. This adds support for recognizing BSON with the new subtype. The BSON library is not responsible for encryption so there is not a need for more support.
Ran
cargo test
bash .evergreen/check-clippy.sh
bash .evergreen/check-rustfmt.sh
=> RUST-453 bson-rust is missing binary subtype 6

examples/deserialize.rs, examples/serialize.rs, fuzz/Cargo.toml, fuzz/fuzz_targets/deserialize.rs, serde-tests/test.rs, src/de/error.rs, src/de/mod.rs, src/de/serde.rs, src/document.rs, src/lib.rs, src/ser/error.rs, src/ser/mod.rs, src/ser/serde.rs, tests/modules/mod.rs, tests/modules/ordered.rs, tests/modules/ser.rs, tests/modules/serializer_deserializer.rs, tests/serde.rs, tests/spec/corpus.rs
This PR updates the bson API language to use "serialize" and "deserialize" in place of "encode" and "decode" respectively.
=> RUST-447 Standardize API with other serde libraries

Cargo.toml, src/bson.rs, src/de/error.rs, src/de/mod.rs, src/document.rs, src/extjson.rs, src/extjson/de.rs, src/extjson/mod.rs, src/extjson/models.rs, src/lib.rs, tests/modules/bson.rs, tests/modules/serializer_deserializer.rs, tests/serde.rs, tests/spec/corpus.rs, tests/spec/mod.rs
[RUST-454](https://jira.mongodb.org/browse/RUST-454)
This PR implements the "decode errors" and "parse errors" sections of the BSON corpus spec tests.
As part of implementing the parse tests, there ended up being far more changes (both in implementation and API) than I would have liked, but I believe they were all necessary. The changes stem from the fact that our current extJSON parser would not fail if extJSON wasn't formatted properly--it would just parse it as a document. The spec's indicate we should actually reject such inputs, which required adding failability to all the extJSON parsing mechanisms (`From<Value> for Bson => TryFrom<Value> for Bson`).
To implement these changes, I started by trying to modify `from_extended_document` to shake the boat as little as possible, but I …
=> RUST-454 Implement error case BSON corpus tests

README.md
This PR fixes the travis badge to point to the correct address and removes the deps.rs badge that seems to be broken.
=> minor: update badges

src/bson.rs, src/extjson/de.rs, src/extjson/models.rs
There were multiple cases where a primitive type was being used as a module, like `f64::NAN`. This was fixed by using the `std` module, like `std::f64::NAN`.
fixes #185
=> fix: Don't use the type for constants; use std

Cargo.toml
- hex -> 0.4.2
- md5 -> 0.7.0
The dependency updates should be innocuous and bring us to the latest version of these crates.
=> Bump dependencies for hex and md5 crates

Cargo.toml, src/oid.rs
1. Timestamp already tested.
2. counter overflow tested by creating an objectID with MAX counter and making sure the counter is MAX. Then created another objectID which incremented the counter to MAX + 1 and made sure it is reset to 0. Found a bug in the code. Fixed that.
3. No fork in Rust.
=> RUST-413 Implementing ObjectId spec tests

README.md, src/lib.rs
The code in the README doesn't work because of the breaking change in 0.8.0. This PR fixes the code so causes less confusion. 
I tested the change by running the code in a small program.
=> Fix code snippet in README

Cargo.toml, src/de/mod.rs, src/document.rs, src/oid.rs, src/ser/mod.rs, src/tests/modules/serializer_deserializer.rs
- Remove unused dependencies (libc, md5)
- Replace the time crate with std equivalent
- Replace the byteorder crate with the std's `{to,from}_{le,be}_bytes` functions on integers
- Some formatting
=> Cleanup deps

src/de/mod.rs, src/tests/spec/mod.rs
RUST-511
This PR updates the trait requirement in `from_bson` to be `DeserializeOwned` instead of `Deserialize<'de>`. Since the function accepts an owned `Bson`, the lifetime constraint wasn't being used, and in fact it was allowing structs that could not be deserialized successfully to be passed to this function and fail at runtime (see #165).
This change is technically breaking, but due to the low probability of this actually affecting user code and its presence basically being a bug, we have decided to make the change. We'll first release it as part of a beta for our next minor version and monitor the community for any instances of breakage.
=> RUST-511 Require DeserializeOwned in from_bson

Cargo.toml
By default cargo publish all the content versionned by git.
following insight given by cargo diet I used an explicit approach
to exclude test dataset etc. from the final package.
=> Exclude unneeded files from built package

src/de/mod.rs, src/lib.rs, src/ser/mod.rs, src/tests/modules/ser.rs, src/tests/modules/serializer_deserializer.rs
[RUST-503](https://jira.mongodb.org/browse/RUST-503)
=> RUST-503 Support serializing directly to Document

src/oid.rs
We already implemented the ObjectId spec tests in RUST-484, so no new tests were added here. The only deviation from the spec I noticed was that we were generating new random bytes for each ObjectId rather than caching them per process, so I've updated the implementation here to cache them.
=> RUST-364 Cache unique process value for oids

src/oid.rs, src/tests/modules/oid.rs
This makes it easier to parse ObjectId in places that expect T: FromStr.
=> RUST-589 Implement FromStr for ObjectId

src/document.rs, src/tests/modules/serializer_deserializer.rs
RUST-648 and #226 
This PR reintroduces support for decoding a `Document` from a stream of bytes that may contain invalid UTF-8 strings. This is useful when reading raw BSON returned from the server, which in rare cases may invalidly truncate it ([SERVER-24007](https://jira.mongodb.org/browse/SERVER-24007)).
=> RUST-648 Reintroduce Document decoding w/ lossy UTF-8 conversion

src/bson.rs, src/document.rs, src/oid.rs, src/tests/modules/bson.rs, src/tests/modules/ordered.rs, src/tests/modules/ser.rs, src/tests/serde.rs
This implements Copy for ObjectId, cleans up places where `oid.clone()` was being used, and updates get_object_id and as_object_id to return owned values, to align with other Copy types (e.g., `.as_f64()`.  That last part is a breaking change, so I've kept it in a separate commit to make it easy to remove from the PR if that's not desired right now.
=> RUST-680 Implement Copy for ObjectId

README.md
The function `decode` is private for `Document`, so will cause a
compiler if following the example. Switch to the `from_reader` function.
=> minor: fix readme example using private function

src/de/mod.rs, src/tests/modules/serializer_deserializer.rs
=> RUST-713 Fix underflow on BSON array and binary deserialization

Cargo.toml
This will fix the ARM build problem (see #132)
=> RUST-709 Update decimal dependency to 2.1.0

Cargo.toml, src/document.rs, src/tests/modules/ordered.rs
RUST-283
This PR updates `Document` to wrap an `IndexMap` (from the `indexmap` crate) instead of `LinkedHashMap` from the now defunct `linked-hash-map` crate.
As part of that, I also updated the `Entry` API to match that of `IndexMap` / `std::HashMap`, since ours used to be slightly different.
=> RUST-283 Replace linked-hash-map with indexmap

src/de/error.rs, src/de/mod.rs, src/document.rs, src/extjson/de.rs, src/oid.rs, src/ser/error.rs, src/ser/serde.rs, src/tests/modules/ser.rs
RUST-738
This PR implements `Clone` on the various error types in the crate. It also updates a few of the error cases to include more information and removes redundant ones.
Once this PR merges, I'll open a companion one on the driver to remove the `Arc` wrappers around the BSON cases.
=> RUST-738 Implement Clone on error types

src/serde_helpers.rs, src/tests/serde.rs
This PR tries to solve an issue I had in a project recently, where 
serializing a String as an ObjectId works fine using the already provided serde_helper function,
but (implicitly) deserializing said ObjectId back to a String would fail.
You can quickly test this by setting up a project with
```rust
[dependencies]
bson = "1.2.2"
serde = "1.0.125"
```
and 
```rust
use bson::serde_helpers::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Serialize, Deserialize)]
struct Test {
#[serde(serialize_with = "serialize_hex_string_as_object_id")]
id: String,
}
fn main() {
let test_struct = Test {
id: "6079529e00b3405c004ea780".to_string(),
};
let doc = bson::to_document(&test_struct).unwrap();
println!("{:#?}", &doc);
let deser_struct: Test = bson::from_document(doc).unwrap(); …
```
=> RUST-747 Add serde helper to deserialize hex string from ObjectId

Cargo.toml, examples/serialize.rs, src/bson.rs, src/de/error.rs, src/de/mod.rs, src/de/serde.rs, src/decimal128.rs, src/document.rs, src/extjson/de.rs, src/extjson/models.rs, src/lib.rs, src/oid.rs, src/ser/error.rs, src/ser/mod.rs, src/ser/serde.rs, src/serde_helpers.rs, src/tests/modules/bson.rs, src/tests/modules/macros.rs, src/tests/modules/oid.rs, src/tests/modules/ordered.rs, src/tests/modules/serializer_deserializer.rs, src/tests/serde.rs
RUST-765 / RUST-789 / RUST-788 / RUST-739
This PR makes a number of breaking changes to the API to ensure it meets the [Rust API Guidelines checklist](https://rust-lang.github.io/api-guidelines/checklist.html).
Notable changes:
- Restructured or eliminated public dependencies on unstable crates to be compatible with future major releases of those crates
- `chrono`:
-  `Bson::DateTime(chrono::DateTime<Utc>)` => `Bson::DateTime(crate::DateTime)`
- removed `pub` from the wrapped `chrono::DateTime` in `bson::DateTime`
- `serde_helpers::chrono_datetime_as_bson_datetime` => `serde_helpers::chrono_0_4_datetime_as_bson_datetime`
- `ObjectId::timestamp` now returns a `crate::DateTime`
- `uuid`:
- `serde_helpers::uuid_as_binary` => `serde_helpers::uuid_0_8_as_binary`
- `hex`: rewrote `oid::Error` …
=> RUST-765 Ensure API meets Rust API guidelines

src/bson.rs, src/ser/error.rs, src/ser/mod.rs, src/tests/modules/bson.rs, src/tests/modules/macros.rs
Hi, there
The auto remove microseconds and nanoseconds feature was removed from This [commit](https://github.com/mongodb/bson-rust/commit/8a92a568ba9de1192e8fb4217ae541c98b335cad#diff-d6adfba5b9892574146927e3f707649f3b601313211502ff5ae3c796f83dcee4L160). I think should add it in the `From<chrono::DateTime<Utc>>` trait, please review it. thank you.
=> RUST-815 Truncate to millisecond precision in `bson::DateTime`'s `From<chrono::DateTime>`

.evergreen/run-tests-chrono.sh, .evergreen/run-tests.sh, Cargo.toml, examples/serialize.rs, src/bson.rs, src/datetime.rs, src/de/error.rs, src/de/mod.rs, src/de/serde.rs, src/extjson/mod.rs, src/extjson/models.rs, src/lib.rs, src/oid.rs, src/ser/serde.rs, src/serde_helpers.rs, src/tests/modules/bson.rs, src/tests/modules/macros.rs, src/tests/modules/ordered.rs, src/tests/modules/serializer_deserializer.rs, src/tests/serde.rs
RUST-811 / #256 / RUST-799 / RUST-825
This PR adds a few methods to `bson::DateTime` to make the conversions between it and `chrono::DateTime` and `std::SystemTime` more obvious / easier to use, as well as to make it more functional on its own. To allow us to make these changes without the fear of polluting the API with old versions of `chrono`, any methods interacting with `chrono` were moved behind the feature flag `"chrono-0_4"`. For consistency, the same was done for `uuid`.
Summary of the new methods:
- `DateTime::now`
- `DateTime::from_millis`
- `DateTime::from_chrono` 
- `DateTime::to_chrono`
- the `to_chrono` and `from_chrono` naming takes inspiration from tokio's [`from_std`](https://docs.rs/tokio/1.6.0/tokio/fs/struct.File.html#method.from_std)
- `DateTime::from_system_time` 
- …
=> RUST-811 Improve ergonomics of `bson::DateTime`

serde-tests/rustfmt.toml, src/bson.rs, src/tests/modules/bson.rs
Implemented `From<Option<T>>` for Bson where `T: Into<Bson>`
Second commit is to suppress an issue on Evergreen's end.
=> RUST-806 Allow conversion of `Option`s to `Bson` types

src/datetime.rs, src/oid.rs, src/ser/error.rs
link to jira: [RUST-838](https://jira.mongodb.org/browse/RUST-838)
https://github.com/mongodb/bson-rust/blob/2e6bb8f4763889728cfe4339d63b817a5c99af5d/src/datetime.rs#L72-L74
because chrono::Utc::now() call SystemTime::now() and NaiveDateTime::from_timestamp
bson::DateTime::now() use SystemTime::now() can prevent **extra performance overhead** on `NaiveDateTime::from_timestamp`
```
pub fn now() -> DateTime<Utc> {
let now =
SystemTime::now().duration_since(UNIX_EPOCH).expect("system time before Unix epoch");
let naive = NaiveDateTime::from_timestamp(now.as_secs() as i64, now.subsec_nanos() as u32);
DateTime::from_utc(naive, Utc)
}
```
chrono source: https://github.com/chronotope/chrono/blob/3467172c31188006147585f6ed3727629d642fed/src/offset/utc.rs#L47-L51
since bson use …
=> RUST-838 Improve bson::DateTime now() performance

src/bson.rs, src/document.rs, src/oid.rs, src/tests/modules/bson.rs
It looks like the only relevant struct which doesn't derive `Debug` is `Document`, so I added support for pretty-print there.
I also added a test to the end of [bson.rs](https://github.com/mongodb/bson-rust/compare/master...NBSquare:RUST-282?expand=1#diff-d3ab75438f3cd06c982a058c8ee3fb9cc79c21af4d8424f6d7c44b3ca5ab5272R312) test.
=> RUST-282 Add pretty-printed `Debug` implementation to `Document`

src/serde_helpers.rs, src/tests/serde.rs
Adds a `serialize_object_id_as_hex_string` serde helper. Note that a deserialize helper is not needed as the implementation of `Deserialize` for `ObjectId` already does this.
=> RUST-868 Add `serialize_object_id_as_hex_string` helper

src/document.rs, src/tests/modules/macros.rs
RUST-876
This PR updates the format produced by `Document`'s `Display` implementation to surround the keys in quotes, as is done in `serde_json` and the shell.
e.g.
```rust
let doc = doc! {
"some": some,
"none": none,
"doc": { "a": 1, "b": true, "c": 3 }
};
println!("{}", doc);
```
now yields:
```json
{ "some": 5, "none": null, "doc": { "a": 1, "b": true, "c": 3 } }
```
=> RUST-876 Quote keys in `Document`'s `Display` format

.evergreen/config.yml, .evergreen/run-tests-decimal128.sh, Cargo.toml, README.md, serde-tests/Cargo.toml, serde-tests/test.rs, src/bson.rs, src/de/mod.rs, src/de/raw.rs, src/de/serde.rs, src/document.rs, src/extjson/mod.rs, src/extjson/models.rs, src/lib.rs, src/oid.rs, src/ser/mod.rs, src/ser/serde.rs, src/tests/spec/corpus.rs
RUST-870
This PR introduces two new functions to the public API which allow for deserializing a `T` directly from raw BSON bytes instead of going through `Document` first: `from_reader` and `from_slice`. The primary goal of these functions is to enable performance improvements in the driver, though they should be generally useful on their own. This PR also enables borrowed deserialization via `from_slice` (#231, RUST-688).
The implementation of this involved introducing a new deserializer that reads directly from raw BSON. The code for this lives in `srd/de/raw.rs`, and is modeled off of the [Implementing a Deserializer](https://serde.rs/impl-deserializer.html) example and `serde_json`'s [`Deserializer`](https://github.com/serde-rs/json/blob/master/src/de.rs#L24). I encourage reading …
=> RUST-870 Support deserializing directly from raw BSON

src/bson.rs, src/extjson/de.rs, src/tests/modules/bson.rs
RUST-882
This PR removes the `From<u64>` impl for `Bson` that could be lossy in the event that the `u64 > i64::MAX`. I opted to not replace it with a `TryFrom` implementation as I would have to specify an error, and I wasn't sure if we wanted to create yet another error type just for this case. An alternative could be to use `<i64 as TryFrom<u64>>::Error`, but I wasn't sure if that would be weird. Let me know what you guys think.
The lossiness in `From<u32>` was fixed in #276.
=> RUST-882 Remove lossy `From<u64>` impl for `Bson`

src/bson.rs, src/de/mod.rs, src/tests/modules/bson.rs, src/tests/modules/ordered.rs, src/tests/modules/ser.rs
RUST-882
This is the `1.2.x` backport fix of RUST-882.
=> RUST-882 Fix lossy `From<u32>` Bson impl, prevent overflow in `From<u64>` (1.2.x)

serde-tests/test.rs, src/oid.rs
RUST-942
This also fixes the test failure inadvertently introduced in #279
=> RUST-942 Generate 5 random bytes instead of 3 for ObjectIds

.evergreen/config.yml, .evergreen/run-tests-decimal128.sh, .evergreen/run-tests-serde.sh, Cargo.toml, serde-tests/Cargo.toml, serde-tests/test.rs, src/bson.rs, src/de/mod.rs, src/de/raw.rs, src/de/serde.rs, src/decimal128.rs, src/document.rs, src/extjson/de.rs, src/extjson/models.rs, src/ser/mod.rs, src/ser/raw/value_serializer.rs, src/ser/serde.rs, src/tests/modules/document.rs, src/tests/modules/ser.rs, src/tests/modules/serializer_deserializer.rs, src/tests/spec/corpus.rs
RUST-960
This PR removes the `decimal128` feature flag and associated functionality. See [this comment](https://github.com/mongodb/bson-rust/issues/282#issuecomment-889958970) for more context on the reasoning behind this.
As part of this, `Decimal128::from_bytes` and `Decimal128::bytes` were introduced, as well as `Document::get_decimal128` and `Document::get_decimal128_mut`. The derived `PartialOrd` implementation was also removed, as it was not correct without the feature flag.
=> RUST-960 Remove the `decimal128` feature flag

src/oid.rs
RUST-942
This backports the change from #284 to the 1.2.x branch.
=> RUST-942 Properly generate 5 random bytes instead of 3 for ObjectIds (1.2.x)

Cargo.toml, src/de/mod.rs, src/decimal128.rs, src/ser/mod.rs, src/tests/modules/ordered.rs, src/tests/modules/ser.rs, src/tests/modules/serializer_deserializer.rs
RUST-960
This PR deprecates the `decimal128` feature flag due to the reasons highlighted in https://github.com/mongodb/bson-rust/issues/282.
semver requires that deprecations happen in minor rather than patch versions, but `decimal128` being "unstable and experimental" means it isn't really bound by semver, so I _think_ we're okay to do this in a patch release. Thoughts?
=> RUST-960 Deprecate `decimal128` feature flag (1.2.x)

src/de/raw.rs, src/de/serde.rs
RUST-889
This PR updates the deserialization logic of `ObjectId` to skip the extended JSON format when deserializing from raw BSON. This is achieved by using the `is_human_readable` method on the deserializer. The changes were largely based on the POC written by @univerz [here](https://github.com/mongodb/bson-rust/issues/264#issuecomment-876266709) (thank you!).
After running the benchmarks provided in that thread, I'm seeing a similar reduction to ~70ns in the `struct<oid> from bytes<struct<oid>>/bson_raw` case.
=> RUST-889 Deserialize `ObjectId` directly from bytes in raw deserializer

.evergreen/config.yml, .evergreen/run-tests-no-default-features.sh, Cargo.toml, serde-tests/Cargo.toml, serde-tests/test.rs, src/ser/error.rs, src/ser/raw/mod.rs, src/ser/serde.rs, src/tests/modules/ser.rs
RUST-968
After some discussion in https://github.com/mongodb/mongo-rust-driver/pull/438, we decided that it was probably best to just remove the `u2i` feature flag altogether, given that it would be difficult and rare for a user to want to manually disable it now that it's the default.
=> RUST-968 Remove `u2i` feature flag

.evergreen/check-rustdoc.sh, .evergreen/config.yml, Cargo.toml, README.md, rustfmt.toml, src/bson.rs, src/datetime.rs, src/de/error.rs, src/de/mod.rs, src/document.rs, src/extjson/de.rs, src/lib.rs, src/ser/error.rs, src/serde_helpers.rs
RUST-736
This PR updates the documentation to account for the 2.0 API, namely the `chrono` and `uuid` changes. As part of that, it also completes RUST-997.
Some other housekeeping changes were made too:
- the "re-exports" section was changed to look like the functions were defined at the top level via `#[doc(inline)]`
- functionality that was gated behind feature flags are now documented
- documentation linting was added to Evergreen
You can see all the new changes in action by running:
```
cargo +nightly rustdoc -p bson --all-features --open -- --cfg docsrs
```
and comparing it to our [latest documentation](https://docs.rs/bson/2.0.0-beta.3/bson/) on docs.rs.
=> RUST-736 Update documentation for 2.0 release

src/de/mod.rs, src/de/raw.rs, src/tests/spec/corpus.rs, src/tests/spec/json/bson-corpus/code.json, src/tests/spec/json/bson-corpus/symbol.json
RUST-943
Previously, the spec tests for these were erroneously giving the serialized form of a string value, not a code or symbol value.  Fixing that uncovered a bug where the intended utf8-lossiness was not being correctly propagated when parsing those.
=> RUST-943 Fix utf8-lossy parsing of code and symbols

src/ser/error.rs, src/ser/mod.rs, src/ser/raw/value_serializer.rs, src/tests/modules/ser.rs, src/tests/spec/corpus.rs, src/tests/spec/json/bson-corpus/binary.json, src/tests/spec/json/bson-corpus/dbref.json, src/tests/spec/json/bson-corpus/document.json, src/tests/spec/json/bson-corpus/regex.json, src/tests/spec/json/bson-corpus/top.json
Validates that any cstrings in BSON (as defined by the [BSON spec](https://bsonspec.org/spec.html)) do not contain null bytes. Rather than enforce this for all of our Rust BSON types (e.g. `Document`, `Regex`) which would be difficult/impossible in some cases, I opted to enforce it when the BSON is encoded into bytes. The entry points for this in our API are `Document::to_reader` and `to_vec`.
=> RUST-908 Validate that C strings do not contain null bytes

src/tests/spec/corpus.rs
The [BSON corpus tests specification](https://github.com/mongodb/specifications/blob/master/source/bson-corpus/bson-corpus.rst#deprecated-types) indicates that we can ignore some fields regarding deprecated types, which causes clippy to complain about unused fields. Rather than delete them, I added `#[allow(dead_code)]` so as not to interfere with `#[serde(deny_unknown_fields)]` (which I also added as it was missing).
=> minor: fix clippy

src/bson.rs, src/lib.rs, src/serde_helpers.rs, src/tests/modules/bson.rs
Refactor Binary serde implementation.  Add Binary constructors consistent with [specs](https://github.com/mongodb/specifications/blob/master/source/uuid.rst).
=> RUST-819 Add methods for converting between Binary and Uuid

src/bson.rs, src/datetime.rs, src/de/error.rs, src/lib.rs, src/serde_helpers.rs, src/tests/datetime.rs, src/tests/mod.rs
[RUST-977](https://jira.mongodb.org/browse/RUST-977)
Add a method to convert a RFC 3339 formatting string to `bson::DateTime` even without the chrono feature flag.
=> RUST-977 Support RFC 3339 to `bson::DateTime` conversion without chrono feature flag

src/raw/test/mod.rs
Changing a method call to `to_rfc3339` to correctly use `to_rfc3339_string` instead.
=> minor: rename to_rfc3339

Cargo.toml
Currently, [`chrono`](https://lib.rs/chrono) depends on a really old version of [`time`](https://lib.rs/time), which is affected by CVE-2020-26235.  
This dependency is withheld by the `oldtime` feature in `chrono`, which is enabled by default.
Unfortunately, Cargo doesn't support disabling specific default features just yet, so the only way to get rid of the default feature is to re-import them all.
Code-wise, all tests seem to pass and I couldn't find any re-exports of the `time` crate (or even `chrono`'s replacements, for that matter), so this shouldn't break the API.
=> deps: Remove `time` transitive dep from chrono

serde-tests/Cargo.toml, serde-tests/test.rs, src/de/mod.rs, src/de/raw.rs, src/de/serde.rs, src/decimal128.rs, src/lib.rs, src/raw/array.rs, src/raw/bson.rs, src/raw/document.rs, src/raw/document_buf.rs, src/raw/mod.rs, src/raw/test/props.rs, src/ser/raw/mod.rs, src/ser/raw/value_serializer.rs, src/ser/serde.rs, src/tests/spec/corpus.rs
RUST-1082
This PR adds `Serialize` and `Deserialize` implementations for the raw BSON types.
e.g. the following is now possible:
``` rust
#[derive(Debug, Deserialize, Serialize)]
struct MyData<'a> {
name: &'a str,
#[serde(borrow)]
binary: RawBinary<'a>,
#[serde(borrow)]
doc: &'a RawDocument,
#[serde(borrow)]
some_field: RawBson<'a>,
}
```
The implementations behave as follows:
- `&RawDocument`:
- for human readable formats: iterate over document and serialize each kvp
- for binary formats: serialize the document as a newtype around a slice of bytes.
- The BSON serializers handle this by interpreting the name of the newtype
- Open Question: should this use something like `{ "$rawBsonDocument": <bytes> }` for binary, non-BSON formats? This will allow `RawBson` to round trip, but that's …
=> RUST-1082 Implement `Serialize` and `Deserialize` for raw BSON types

src/de/serde.rs
This fixes an issue caused by some changes made in the raw BSON `Serialize`/`Deserialize` PR. I think the changes were meant as a minor improvement, but they accidentally broke deserialization of `Binary` in a `#[serde(flatten)]` chain. I've just gone ahead and reverted it to what it was before.
=> minor: fix `Binary` deserialization with `serde(flatten)`

serde-tests/options.rs, serde-tests/test.rs, src/bson.rs, src/de/mod.rs, src/de/raw.rs, src/de/serde.rs, src/lib.rs, src/raw/bson.rs, src/raw/document.rs, src/ser/mod.rs, src/ser/serde.rs
RUST-1022
This PR introduces two new options structs that enable users to configure `Serializer` and `Deserializer` (used in `to_bson` and `from_bson`) to be considered not-human-readable, just as the raw serializer/deserializer is (used in `to_vec` and `from_slice`). As part of that, several `to_x_with_options` functions were introduced.
=> RUST-1022 Support configuring `Serializer` and `Deserializer` to be non-human-readable

Cargo.toml, README.md, serde-tests/Cargo.toml, serde-tests/test.rs, src/datetime.rs, src/lib.rs, src/uuid/mod.rs
RUST-1024
This PR adds support for serializing/deserializing `uuid::Uuid` and `chrono::DateTime` as `bson::Uuid` and `bson::DateTime` respectively. This improves upon the existing serde helpers by including support for nested types, such as `Option<uuid::Uuid>`.
=> RUST-1024 Add `serde_with` integration for `Uuid` and `DateTime`

serde-tests/test.rs, src/lib.rs, src/raw/array.rs, src/raw/document.rs, src/raw/document_buf.rs, src/raw/mod.rs
This PR hides the not yet complete raw BSON API from the public API in preparation for the 2.1 release. The raw BSON stuff will land in 2.2 instead.
I've gone ahead and made a `2.1.x` branch which this will merge into, since master won't need to have these changes in it.
evg patch: https://evergreen.mongodb.com/version/618ed47757e85a14b56c83e1
=> minor: hide work-in-progress raw BSON API

src/bson.rs
Hi,
It seems that relaxed extended json doesn't work for arrays, here is an example:
```rust
use bson::serde_helpers::chrono_datetime_as_bson_datetime;
use serde_json::Value;
use chrono::Utc;
use chrono::TimeZone;
use serde::{
Deserialize,
Serialize,
};
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct Foo {
#[serde(with = "chrono_datetime_as_bson_datetime")]
pub date: chrono::DateTime<Utc>,
}
fn main() {
let foo = Foo {
date: Utc.ymd(2018, 1, 1).and_hms(0, 0, 0),
};
let bson = bson::to_bson(&foo).unwrap();
let expected: Value = serde_json::from_str(r#"{"date":{"$date": "2018-01-01T00:00:00Z"}}"#).unwrap();
println!("{:?}", expected); //Object({"date": Object({"$date": String("2018-01-01T00:00:00Z")})})
assert_eq!(expected, bson.into_relaxed_extjson()); // WORK
let list = …
```
=> RUST-1107 Fix array relaxed extended json

src/macros.rs, src/raw/document.rs, src/raw/test/append.rs, src/raw/test/mod.rs, src/tests/modules/macros.rs
RUST-1109
This PR implements the `rawbson!` and `rawdoc!` macros to allow easier creation of raw BSON types. They are largely copy/pasted from the existing `bson!` and `doc!` macros with just a few modifications to build raw BSON. This PR also updates a number of examples and tests to use `rawdoc!` instead of building `RawDocumentBuf` values manually or from `Document`.
=> RUST-1109 Implement `rawbson!` and `rawdoc!` macros

src/lib.rs, src/ser/mod.rs
RUST-1119
This PR adds the `bson::to_raw_document_buf` convenience function. I originally set out to also add `bson::to_raw_bson` as well (RUST-1110), but it looked like it was going to be a lot of effort for functionality that might not be all that useful. For now, I've split off just this function (which definitely will be useful) and am putting the `to_raw_bson` work on the backburner. Let me know if that sounds okay.
=> RUST-1119 Add `bson::to_raw_document_buf` function

serde-tests/test.rs, src/bson.rs, src/de/mod.rs, src/de/raw.rs, src/de/serde.rs, src/lib.rs, src/tests/spec/corpus.rs
RUST-1111
This PR adds support to the `Bson`-based deserializer (used in `bson::from_bson` and `bson::from_document`) for deserializing the owned raw BSON types, namely `RawBson`, `RawDocumentBuf`, and `RawArrayBuf`.
=> RUST-1111 Support deserializing `RawBson` from `Bson`

src/bson.rs, src/raw/array.rs, src/raw/bson_ref.rs, src/raw/document.rs, src/raw/document_buf.rs, src/raw/serde.rs, src/raw/test/mod.rs, src/ser/raw/mod.rs
This PR implements a few minor performance and API improvements to the raw BSON API that I noticed while benchmarking it / using it in the driver.
- `RawDocumentBuf::append` accepts and `impl AsRef<str>` for the key instead of an `impl Into<String>`
- this allows us to avoid an allocation when we have string reference types
- we can't really move a string into our buffer anyways, so for owned strings there isn't any perf penalty here
- this also applies to the `FromIterator` implementation for `RawDocumentBuf`
- exposed all fields of `RawJavaScriptCodeWithScopeRef` and `RawRegexRef`
- this is in line with other similar types
- the getters were removed as part of this
=> minor: minor raw BSON perf and API improvements

.evergreen/config.yml, .evergreen/install-fuzzer.sh, .evergreen/run-fuzzer.sh, fuzz/Cargo.toml, fuzz/fuzz_targets/iterate.rs, fuzz/fuzz_targets/raw_deserialize.rs, src/de/raw.rs, src/raw/iter.rs, src/raw/mod.rs
RUST-939
This PR begins running the existing fuzzer in evergreen, and it also runs some new fuzzing targets intended for the new raw BSON API. As part of that, it found some crashes which have also been fixed in this PR.
=> RUST-939 Run BSON fuzzer in Evergreen

src/uuid/mod.rs
Add traits that exist in `uuid::Uuid` but were missing in `bson::Uuid`.
This is particularly useful for usage in a `HashMap` where `Eq` is required for most methods.
=> RUST-1195 Add missing trait impls to `Uuid`

serde-tests/test.rs, src/de/raw.rs
RUST-1243
Prior to this PR, all keys were treated as strings, so the deserialization would fail with "invalid type: string \"Key\", expected enum Enum".  This bug doesn't occur when deserializing from the parsed Bson types because that one uses the main deserializer to parse the key (which knows how to handle enum values) rather than a specialized one.
=> RUST-1243 Handle enum keys when deserializing a map from binary

.evergreen/config.yml, .evergreen/run-tests.sh, Cargo.toml, src/bson.rs, src/datetime.rs, src/extjson/models.rs, src/lib.rs, src/oid.rs, src/raw/test/mod.rs, src/serde_helpers.rs, src/tests/datetime.rs, src/tests/modules/bson.rs, src/tests/modules/document.rs, src/tests/modules/macros.rs, src/tests/modules/serializer_deserializer.rs, src/tests/serde.rs, src/tests/spec/corpus.rs
RUST-1129
This PR swaps out the internal operations that used `chrono` for equivalent ones using `time`, makes the `chrono` dependency optional, and adds optional interop methods for `time` structs.
=> RUST-1129 Make the dependency on `chrono` optional and provide equivalent `time` interop

src/bson.rs, src/raw/bson_ref.rs
RUST-1385
This makes public the existing `Binary::as_raw_binary`, and adds the reciprocal `RawBinaryRef::to_binary`.  Tagging RUST-1385 because I noticed these didn't exist during implementation of that :)
=> RUST-1385 Add binary/raw conversions

src/ser/raw/document_serializer.rs
RUST-1062
This PR updates the array serialization logic in the raw document serializer to avoid unnecessary heap allocations, resulting in an ~8% improvement in performance in a simple benchmark I'm using.
The solution used here is a bit different than the originally proposed one to just push bytes directly onto the buffer, but it was necessary in order to preserve the expected byte order (pushing them would result in a backwards string). As a result, the performance improvements were not as significant as originally envisioned unfortunately.
=> RUST-1062 More efficiently serialize array indexes

src/de/serde.rs
I believe this was a bug as try_from has this functionality--while from_slice had functionality that failed on fractions.  Either this is the proper decode fix, or the encoding needs fixed where .fract() adds ".0" to string.
=> Double canonical extended json fraction fails round trip on Deserialize from_slice

README.md
The links in the feature flags table in the README weren't absolute URLs, so they went to a GitHub 404 page.
=> Fix links in the Feature Flags table.

src/serde_helpers.rs, src/tests/serde.rs
This is a follow on PR to #381 which renames the new `i64_as_datetime` helper to `i64_as_bson_datetime`, which more closely matches our existing helpers. The "bson" portion helps differentiate between different datetime types that we have support for, such as those from `chrono`.
=> RUST-1540 Rename `i64_as_datetime` to `i64_as_bson_datetime`

src/de/raw.rs, src/tests/serde.rs
RUST-1564
This was found in prepping for the 2.5.0 release; it's unrelated to changes in that release but seemed good to fix before rolling that out.
=> RUST-1564 Fix a fuzzer-found failure

src/datetime.rs, src/oid.rs
Addresses #392 
To see what the new docs look like, you can run `cargo doc --open`. Some of the `chrono` hyperlinks are broken when generating the docs that way, but I think that's not the case when docs.rs actually generates them.
=> minor: improve serde documentation of `DateTime` and `ObjectId`

.evergreen/config.yml, Cargo.toml, serde-tests/json.rs, src/bson.rs, src/de/serde.rs, src/decimal128.rs, src/extjson/de.rs, src/extjson/models.rs, src/lib.rs, src/ser/serde.rs, src/tests/spec/corpus.rs
RUST-1592
This adds support for the standard human-readable string traits (`Display` and `FromStr`) to `Decimal128` via an intermediate `ParsedDecimal128` struct, as well as using such in the extjson format.  While it's possible to generate/parse the strings directly from the packed binary representation, I opted for the intermediate struct because it's _way_ more readable and it'll be useful if we ever want to support more operations.
=> RUST-1592 Support decimal128 to/from human-readable strings

.evergreen/check-wasm.sh, .evergreen/config.yml, .evergreen/run-wasm-tests.sh, Cargo.toml, src/oid.rs, wasm-test/Cargo.toml, wasm-test/src/lib.rs, wasm-test/src/test.rs
RUST-504 / RUST-1130
This adds support for using the Javascript environment timestamp when constructing an `ObjectId` when compiled to wasm, and a simple test case and the supporting machinery.  This supersedes #405.
=> RUST-504 Use js timestamps when generating objectids

src/datetime.rs, src/tests/datetime.rs
Adds `checked_duration_since` and `saturating_duration_since` methods to `crate::DateTime`. These are based off of the methods of the same name in `std::time::Instant`. I chose not to add any `Sub` implementation because we'd need to decide what to do when the result is negative (i.e. panic or return 0); I'd rather let users make this decision explicitly.
=> RUST-1677 Add duration_since methods to `DateTime`

src/oid.rs
=> use random() directly in gen_process_id

.evergreen/compile-only.sh, .evergreen/config.yml, Cargo.toml, src/oid.rs
See https://github.com/mongodb/bson-rust/pull/442#issuecomment-1851849879:
> This [broke the 2.8.0 release on `wasm32-wasi` targets](https://github.com/graphql-rust/juniper/actions/runs/7173028592/job/19531503717#step:4:171):
> 
> ```
>  error[E0433]: failed to resolve: use of undeclared type `SystemTime`
>    --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bson-2.8.0/src/oid.rs:245:30
>     |
> 245 |         let timestamp: u32 = SystemTime::now()
>     |                              ^^^^^^^^^^ use of undeclared type `SystemTime`
>     |
> help: consider importing this struct
>     |
> 4   + use std::time::SystemTime;
>     |
> 
> error[E0433]: failed to resolve: use of undeclared type `SystemTime`
>    --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15 …
```
=> Fix compilation on `wasm32-wasi` target

src/uuid/mod.rs
The feature is named `serde_with-3`. The `_` makes it such that the `SerializeAs` implementation is not working. The `DeserializeAs` implementation above uses the correct feature name and shows up in the documentation.
=> Fix feature name for serde_with Uuid implementation

src/spec.rs, src/tests/binary_subtype.rs, src/tests/spec/json/bson-corpus/binary.json
- Sync BSON corpus test
- Implement and test BinarySubtype::Sensitive which maps to 0x08
=> RUST-1716 Add BSON Binary Data subtype Sensitive

src/de/raw.rs
RUST-1850
This is the same issue that caused RUST-1564, with the same fix: don't assume deserializer state is in any way valid after an error.  I looked for other instances of this pattern that would have the same problem but didn't find any.
=> RUST-1850 Fix a fuzzer failure

src/raw/iter.rs, src/raw/mod.rs
Missed that exports had to be explicitly re-exported in #449.
=> fix: export RawElement type

src/raw/array_buf.rs, src/raw/document_buf.rs
RUST-1512
This adds `RawDocumentBuf::append_ref`, providing a method equivalent to `append` for borrowed data.  This can be useful for avoiding the need for intermediate buffers when the source data is borrowed.
=> RUST-1512 Provide a method to append a borrowed value

src/de/raw.rs, src/de/serde.rs, src/uuid/test.rs
Fix for the bug report in #467.
=> RUST-1899 Fix UUID string deserialization

rustfmt.toml, src/de/raw.rs, src/de/serde.rs, src/ser/raw/mod.rs, src/ser/serde.rs, src/serde_helpers.rs, src/tests/mod.rs, src/tests/serde_helpers.rs
RUST-1764
This wrapper removes the need for the `human_readable_serialization` option for `Collection` and provides more granular control as well.  There could hypothetically also be a use for a corresponding `NonHumanReadable` wrapper but I'd prefer to wait on adding that until someone asks for it.
=> RUST-1764 Add `HumanReadable` convenience wrapper

src/raw/iter.rs
Without the annotation it gets a lifetime bound to the `RawElement` struct, not the underlying data.
=> minor: fix lifetime of RawElement::key

src/de/serde.rs, src/extjson/models.rs, src/tests/serde.rs
This PR updates the extended JSON deserializer to support the `$uuid` documented [here](https://github.com/mongodb/specifications/blob/master/source/extended-json.rst#special-rules-for-parsing-uuid-fields). As noted in the ticket, this behavior now required for the Atlas SQL team. I confirmed locally that this change works for our purposes.
Looking through the code, it seems `$uuid` _is_ supported in several other places but not for direct `serde_json::from_str::<bson::Bson>` parsing. I assume this was an accidental omission and not a deliberate choice.
I was unsure exactly where/how to test this. I spent a lot of time looking through the test files but I never quite figured out how/where/if you are testing this specific behavior (parsing extended json strings directly into `Bson` …
=> RUST-1933: Support deserializing $uuid extended JSON syntax

src/de/raw.rs, src/decimal128.rs, src/ser/serde.rs, src/tests/spec/corpus.rs
RUST-426
This is a bugfix tangential to working on RUST-426; it conveniently showcases the complexity of issues the current state of the codebase can cause.
* In the process of documenting serialization behavior, I noticed that `Decimal128` had both inline serialization code in `Bson::serialize` and its own `Serialize` implementation.
* The behavior between those two differed: `Decimal128::serialize` uses the proper extjson representation when the serializer is human-readable, whereas `Bson::serialize` would always use a non-human-readable format (a holdover from before we had proper support for Decimal128 values).
* Fixing that to always use `Decimal128::serialize` caused a corpus test to start failing.
It turns out that in the corpus tests, along with the spec-mandated comparisons, we …
=> RUST-426 Fix Decimal128 human-readable serialization

src/datetime.rs, src/raw/serde.rs, src/raw/serde/bson_visitor.rs, src/raw/serde/seeded_visitor.rs
RUST-1773
This puts responsibility for turning a Serde map into bson values squarely on `OwnedOrBorrowedRawBsonVisitor`; `SeededVisitor`'s job is now to efficiently buffer those values.
In my plan for the 🎆Glorious Future🎆, `OwnedOrBorrowedRawBsonVisitor` will also be taking over for the other places that parse extjson (`BsonVisitor`, `TryFrom<serde_json::Value>`, `crate::extjson::models`) and will necessarily be getting more liberal in the forms it accepts, so this means that doesn't need to be mirrored in `SeededVisitor` as well.
With this, I think the separation of logic is clear enough that there's no need to further merge; the reasoning from your original work on why that would involve quite a bit of complication is still very valid.
=> RUST-1773 Merge duplicate extjson map parsing between OwnedOrBorrowedRawBsonVisitor and SeededVisitor

src/de/error.rs, src/de/mod.rs, src/de/raw.rs, src/document.rs, src/raw/array.rs, src/raw/document.rs, src/raw/iter.rs, src/raw/mod.rs, src/raw/test/mod.rs, src/tests/spec/corpus.rs
RUST-1992
This removes quite a bit of duplicated binary parsing code and brings us closer to having separation of concerns between binary parsing and serde deserialization.  IMO, the deserializer and helper structs are now easier to understand as well - rather than a mutable "root deserializer" that's threaded downwards, each deserializer or access struct just gets an immutable ref to the thing it's mapping into serde.
=> RUST-1992 Convert raw deserializer to use raw document iteration

src/de/error.rs, src/de/mod.rs, src/de/raw.rs, src/document.rs, src/raw/document.rs, src/raw/error.rs, src/raw/iter.rs, src/raw/mod.rs
RUST-1992
This PR:
* Relocates the remaining raw field parsing from `crate::de` to `crate::raw` to go with the existing other such functions there
* Removes duplicate "read length and contents to buffer" logic from `crate::document` in favor of the function in `crate::de`.
* Cleans up error construction a little bit.
=> RUST-1992 Minor parsing cleanup

src/raw/document_buf.rs, src/raw/document_buf/raw_writer.rs, src/raw/serde/seeded_visitor.rs, src/ser/mod.rs, src/ser/raw/mod.rs, src/ser/raw/value_serializer.rs
RUST-1992
This takes the actual "write to buffer as bytes" code out of `RawDocumentBuf`; my theory is that `RawSerializer` can be reworked to a wrapper around `RawWriter` the way `RawDeserializer` is for `RawElement`.  Even if I'm wrong, I think this is a little cleaner.
I also pruned some string-writing utilities that had proliferated a bit.
=> RUST-1992 Factor raw bson encoding out of RawDocumentBuf

Cargo.toml, README.md, src/binary.rs, src/bson.rs, src/decimal128.rs, src/document.rs, src/tests/modules/bson.rs
#494
Summery of changes:
* Added feature `hashable` to require the user to choose to opt-in using `Bson` as hash key.
Although, `serde_json` didn't bother with having this behind the feature flag, so If you like I can remove it.
* `Bson::Double(f64)` - implemented the same solution as [`serde_json`](https://docs.rs/serde_json/1.0.127/src/serde_json/number.rs.html#53-70).
* `Bson::Document(Document)` - implemented the same solution as [`serde_json`](https://docs.rs/serde_json/1.0.127/src/serde_json/map.rs.html#395-397).
* `Bson::JavaScriptCodeWithScope(JavaScriptCodeWithScope)` - Able to impl Hash/Eq only if Document is impl Hash/Eq.
* `Bson::{RegularExpression(Regex), Binary(Binary), Decimal128(Decimal128), DbPointer(DbPointer)}` - Added Derive Hash/Eq without feature flag `hashable`, no …
=> RUST-2027 Impl Hash/Eq for BSON

src/decimal128.rs, src/raw/test/mod.rs
Fix Decimal128 panic when parsing strings w/o a char boundary at idx 34 (Coefficient::MAX_DIGITS).
=> RUST-2028 Fix Decimal128 panic when parsing strings w/o a char boundary at idx 34

fuzz/Cargo.toml, fuzz/fuzz_targets/iterate.rs, fuzz/fuzz_targets/raw_deserialize.rs, fuzz/fuzz_targets/raw_deserialize_utf8_lossy.rs
Runs `to_writer` in fuzz tests. Makes the fuzzer slower, but covers any write errors. Also adds a fuzz test for `from_slice_utf8_lossy`.
Note: I did not check for equivalence in `from_reader` and `to_writer`, as, even for accounting for length, there is still some loss in data ordering from the reader, as is to be expected.
=> test(fuzz): read -> write bson

.evergreen/run-fuzzer.sh, fuzz/Cargo.toml
Missing malformed_length target is causing build failure at oss-fuzz
=> fuzz: remove malformed_length entry

.evergreen/compile-only.sh, .evergreen/run-wasm-tests.sh
RUST-2058
There were two unrelated issues here:
* The `wasm32-wasi` target was renamed in newer versions of rustc to `wasm32-wasip1` (to make room for the upcoming `wasm32-wasip2`), so we need conditional logic for that.
* The version of LLVM used in rustc 1.82+ emits webassembly using a reference types specification that's not supported in the node.js runtime ([this bug](https://github.com/rustwasm/wasm-bindgen/issues/4211) has some details).  I've pinned that test to rustc 1.81 for now; hopefully by the time our MSRV catches up to that and we need to unpin it node will have also caught up :)
=> RUST-2058 Fix BSON WASM tests

src/tests/spec/json/bson-binary-vector/README.md, src/tests/spec/json/bson-binary-vector/float32.json, src/tests/spec/json/bson-binary-vector/int8.json, src/tests/spec/json/bson-binary-vector/packed_bit.json, src/tests/spec/vector.rs
=> RUST-2149 Sync additional vector tests

Cargo.toml, src/oid.rs
- update edition
- removed deprecated function [`rand::thread_rng`](https://docs.rs/rand/0.9.0/rand/fn.thread_rng.html)
=> RUST-2158 update edition & rand crate

src/extjson/models.rs, src/tests/serde.rs
According to the specification, there exists a legacy Extended JSON form of Datetime
https://github.com/mongodb/specifications/blob/master/source/extended-json/extended-json.md#datetime
> Mongoexport 2.4 and the Java driver always transform a Datetime object into an Extended JSON string of the form `{"$date": <ms since epoch>}`. This form has the problem of a potential loss of precision or range on the Datetimes that can be represented.
Specially, this legacy form is called `JsonMode.STRICT` in the Java `JsonWriterSettings`, while the canonical form is `JsonMode.EXTENDED`. The former is still used by the Debezium connector for MongoDB.
This PR adds the ability to parse such legacy format, without conflicting with the standard ones.
=> RUST-2174 feat(extjson): parse legacy `{"$date": <ms since epoch>}`

README.md
RUST-1375
Updating to match the change in https://github.com/mongodb/mongo-rust-driver/commit/5b603f25432ccff914dcfd9a85cf9cf83562c1a5.
=> RUST-1375 Update bson crate MSRV policy

Cargo.toml, README.md, src/de/mod.rs
For various projects I'm working on, I'm using BSON as an efficient means to transfer potentially quite a bit of data (~200Mb). From what I can read of the BSON standard, it's expected to support document sizes up to 2Gb, but this implementation is currently hard capped to 16Mb to better service MongoDB.
I figured adding an opt-in feature to increase the cap to the maximum would serve to be useful for more people than just me, without affecting the way that it's currently used within MongoDB applications.
I ran all the unit tests and linting tests and didn't encountered any failures with or without the added feature enabled.
Let me know if I'm off-base thinking that this is a useful addition, or if there are any unforseen issues with expanding the max size. I haven't done extensive …
=> add `uncapped_max_size` feature to allow increasing max BSON size

Cargo.lock, Cargo.toml, README.md, serde-tests/Cargo.lock, serde-tests/Cargo.toml, src/bson.rs, src/serde_helpers.rs, src/tests/serde.rs, src/uuid/mod.rs, src/uuid/test.rs
I left the remaining feature flag name as `uuid-1` in case we need to support `uuid-2` in the future.
=> RUST-1380 Drop support for uuid 0.8

.github/dependabot.yml
Example PR: https://github.com/isabelatkinson/bson-rust/pull/1
Patch: https://spruce.mongodb.com/version/68375dc997e7750007ff0f95/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> RUST-577 Bump dependencies with dependabot

fuzz/fuzz_targets/serialization.rs
RUST-2213
There was already code to consider `NaN`s equal as values in `Document`s but it wasn't recursing into `Array`s; all of the fuzzer failures we've seen recently have actually been some flavor of `Array([NaN,...])`.  I also added a case for `JavaScriptCodeWithScope` because that could hypothetically have the same failure, although I don't think we've actually seen it.
=> RUST-2213 Properly handle NaNs in fuzz testing

Cargo.lock, Cargo.toml, src/raw/error.rs, src/raw/mod.rs
RUST-1798
Our string parsing has changed pretty significantly since #440 was opened, so I opted to create a new PR rather than try to rebase and rework that one.
=> RUST-1798 use simd to optimize utf8 validation

Cargo.lock, Cargo.toml, serde-tests/Cargo.lock, src/document.rs, src/error.rs, src/lib.rs, src/raw.rs, src/raw/array.rs, src/raw/document.rs, src/raw/error.rs, src/raw/test.rs, src/tests/modules/document.rs
RUST-1406
This PR introduces crate-wide `Error` and `Result` types, which are modeled on the equivalent types in the driver, and does the first pass of error conversions for the `Document` and `RawDocument` getter methods. I also did a bit of documentation cleanup for the `Document` methods. I will follow up with more PRs to port over the rest of the error types and finalize the design/documentation of the new types.
=> RUST-1406 Add crate-wide error types, convert value access errors

src/raw.rs, src/raw/bson_ref.rs, src/raw/document_buf.rs
RUST-1887
This uses the technique described in [Alternative Blanket Implementations for a Single Rust Trait](https://www.greyblake.com/blog/alternative-blanket-implementations-for-single-rust-trait/) to remove the requirement for users to implement the unusual `bind` trait method for custom types if they want to use them in `rawdoc!` macros; instead a very small boilerplate impl can now be used.  This does complicate the internal type machinery a bit (introduction of a helper trait and some wrapper types for type-level dispatch) but those don't need to be visible and they're well contained.
=> RUST-1887 Make BindRawBsonRef a little more user-friendly

src/de/raw.rs, src/raw.rs, src/raw/cstr.rs, src/raw/document.rs, src/raw/document_buf.rs, src/raw/iter.rs, src/raw/test.rs
RUST-1992
In the process of updating the driver for the `CStr` changes, I ran across a bunch of things (missing stdlib `impls` mostly) that needed to be fixed in the `bson` crate first.
=> RUST-1992 Updates to allow the driver to be updated

Cargo.lock, Cargo.toml, src/bson.rs, src/datetime.rs, src/lib.rs, src/serde_helpers.rs, src/tests/modules/bson.rs, src/tests/modules/serializer_deserializer.rs, src/tests/serde.rs
Hi!
This PR introduces interoperability with the `jiff` ([docs](https://docs.rs/jiff/0.2.15/jiff/)) crate by adding helpers to convert between `jiff::Timestamp` and `bson::DateTime`. This allows users of `jiff`, a modern and standards-focused time library, to seamlessly serialize and deserialize timestamps with BSON, I followed the already present integration with `chrono` to add features and tests.
**Changes included:**
* **Optional Dependency**: Added `jiff` as an optional dependency under the `jiff-0_2` feature flag.
* **Serde Helper**: Created a new `serde_with` helper, `datetime::FromJiff02Timestamp`, to enable ergonomic serialization for structs (e.g., `#[serde_as(as = "datetime::FromJiff02Timestamp")]`).
* **Direct Conversions**: Added `DateTime::from_jiff()` and …
=> feat: Add integration with `jiff::Timestamp`

src/lib.rs
RUST-1985
This started as adding the warning that other formats are not promised to work but grew as I noticed other things that needed to be revised as well with the 3.0 changes.
=> RUST-1985 Update bson toplevel rustdoc

src/lib.rs
same issue as https://github.com/mongodb/mongo-rust-driver/pull/1483
=> minor: replace doc_auto_cfg with doc_cfg
