tests/modules/bson.rs, tests/modules/mod.rs
Easier to realize with example how to use `to_json`
=> Add to_json test and example

tests/modules/bson.rs, tests/modules/encoder.rs, tests/modules/macros.rs, tests/modules/ordered.rs
Sorry, total OCD pull request :-). Would still be nice to merge though.
=> Some whitespace fixes

src/ordered.rs
This is needed to make full integration with the Mongo driver possible.
=> Implement Debug, Display and Error for ValueAccessError

src/ordered.rs, tests/modules/ordered.rs
In a similar way as the existing accessors.
=> Add get binary generic accessor

.travis.yml, serde-tests/Cargo.toml, serde-tests/build.rs, serde-tests/test.rs.in, src/decoder/serde.rs, src/encoder/serde.rs
=> Improved enum support, fixes on serde tests

src/bson.rs
Also add more useful documents.
=> add getter helpers for Bson, correct implementation for #57

Cargo.toml, examples/encode.rs, src/bson.rs, src/decoder/mod.rs, src/ordered.rs, tests/lib.rs, tests/modules/encoder_decoder.rs, tests/modules/ordered.rs, tests/serde.rs
I followed the changes listed in https://github.com/chronotope/chrono/blob/master/CHANGELOG.md#040-2017-06-22.
=> Upgrade chrono deps to v0.4

serde-tests/test.rs, src/bson.rs, src/decoder/mod.rs, src/decoder/serde.rs, src/encoder/mod.rs, src/encoder/serde.rs, src/oid.rs, src/ordered.rs
I've simply replaced the `try!` macro with the `?` operator.
=> Replaced all occurences of `try!(.*)` with `?`.

src/bson.rs
Sorry, slipped over these yesterday. Also, disregard the previous PR (#101) with the same content as this one, I messed up Git…
=> More small improvements

fuzz/.gitignore, fuzz/Cargo.toml, fuzz/fuzz_targets/decode.rs, src/decoder/mod.rs, tests/modules/encoder_decoder.rs
This PR adds a simple fuzzer, one failing test case I found with it and a what I think could be a fix.  I don't know BSON's wire protocol well, so my fix should be treated as suspect.
=> Fix for #116

Cargo.toml, README.md, src/encoder/serde.rs, src/lib.rs
This updates the dependencies of bson and replaces try_from by a builtin std feature.
=> Update dependencies and replace try_from by std builtin

README.md
Update README to reflect the latest version.
=> Bump installation version to 0.14 in the readme.

src/oid.rs
added a getter for timestamp and a test for the same
=> RUST-475 adding getter for timestamp from ObjectId

README.md
=> Update version number in readme

src/oid.rs
=> RUST-826 Take ownership of `self` in `ObjectId::to_hex`

README.md
=> Grammar fix in README

src/de/serde.rs
The use of `deserialize_any` is incompatible with data formats that are not self-describing. This PR removes the call to `deserialize_any` in our implementation of `Deserialize` for `ObjectId` to be more compatible with other data types.
=> RUST-861 Remove use of `deserialize_any` in `ObjectId` deserialization

src/ser/raw/mod.rs
=> RUST-1009 Return false from `is_human_readable` in raw serializer

src/serde_helpers.rs, src/tests/serde.rs
=> impl i64_as_datetime

src/de/serde.rs
I didn't notice that this was contributed to the 2.4.x branch, so it never made it to main.
=> Fix double extjson deserialization (#386)

src/de/serde.rs
Co-authored-by: mitchrmiller <69634302+mitchrmiller@users.noreply.github.com>
=> Fix double extjson deserialization (#386) (#395)

src/de/raw.rs, src/de/serde.rs, src/tests/serde.rs
This merges the bugfixes for RUST-1564 and the contributed double deserialization fix into the release branch for 2.5.x.
=> Merge changes from main

src/lib.rs
This table was out of date/had broken links -- would like to get the fix in prior to releasing 2.6.
=> RUST-1613 Update feature flags table

src/raw/mod.rs
=> Fix check-rustdoc

.evergreen/compile-only.sh, .evergreen/config.yml, Cargo.toml, src/oid.rs
=> Fix compilation on `wasm32-wasi` target (#445)

src/bson.rs
To match the `From<&T>` implementation.
=> Implement From<&mut T> for Bson

Cargo.toml, README.md, src/lib.rs
=> release v2.15.0
